
import "./global.css";
import RecoidContextProvider from "./recoilContextProvider";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
     <RecoidContextProvider><body style={{background:'ivory'}}>{children}</body></RecoidContextProvider>
    </html>
  )
}
